-- =====================================================================
-- StudyReach : instantané du schéma Supabase (projet bwaoxwfkqqpqvtpynwzh)
-- Exporté le 2026-10-09. NE CONTIENT AUCUNE DONNÉE, uniquement la structure.
--
-- Sert de sauvegarde / documentation de la base. Ce n'est PAS une migration
-- (volontairement hors de supabase/migrations/ pour ne pas casser l'historique
-- Supabase). Pour recréer la base sur un projet vide : exécuter ce fichier
-- dans le SQL Editor de Supabase.
--
-- Ordre : extensions > tables > contraintes > index > fonctions > triggers
--         > RLS + policies > vues > droits > storage > tâches cron.
--
-- Non inclus (à refaire à la main sur un nouveau projet) :
--   - les Edge Functions (check-noshow-slots, check-validation-deadlines,
--     daily-signup-digest, expire-participations, send-email, ...)
--   - les réglages Auth (templates email, protection mots de passe, etc.)
--   - les variables d'environnement / secrets
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Extensions
-- ---------------------------------------------------------------------
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;
create extension if not exists pg_cron;
create extension if not exists pg_net;
create extension if not exists http;

-- ---------------------------------------------------------------------
-- 2. Tables
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  created_at timestamp with time zone default now() not null,
  email text,
  first_name text,
  last_name text,
  role text,
  company text,
  wallet numeric default '0'::numeric,
  profession text,
  age text,
  region text,
  themes jsonb,
  id uuid not null,
  bio text,
  birth_date date,
  genre text,
  city text,
  country text,
  nationality text,
  handicap text,
  status_pro text,
  sector text,
  education text,
  company_size text,
  seniority text,
  devices text[],
  os text[],
  app_usage text,
  tech_level text,
  connection_speed text,
  social_networks text[],
  has_participated boolean default false,
  has_camera boolean default false,
  languages text[],
  mobile boolean default false,
  long_term boolean default false,
  sport text,
  diet text,
  smoker text,
  alcohol text,
  medical_follow boolean default false,
  chronic_illness text,
  income text,
  online_purchase_freq text,
  has_car boolean default false,
  subscriptions text[],
  grocery_budget text,
  brand_preference text,
  financial_products boolean default false,
  family_status text,
  children_count text,
  housing_status text,
  housing_type text,
  screen_time text,
  media_consumption text[],
  social_frequency text,
  creative_hobby text,
  suspended boolean default false not null,
  phone text,
  email_verified boolean default false not null,
  verification_token text,
  stripe_account_id text,
  lang text,
  payout_fingerprint text,
  flagged_duplicate boolean default false not null,
  pending_email text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer_url text,
  profession_other text
);

create table if not exists public.studies (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  theme text,
  duration text,
  mode text,
  link text,
  cost_per_participant numeric,
  researcher_id uuid default gen_random_uuid(),
  status text default 'active'::text,
  study_type text,
  link_ai boolean default false,
  target_criteria jsonb,
  max_participants integer default 10,
  prescreening jsonb default '[]'::jsonb,
  ai boolean default false,
  description text,
  ai_focus text,
  ai_response_format jsonb default '{"tts": false, "audio": false, "video": false}'::jsonb,
  global_synthesis text,
  budget numeric generated always as (cost_per_participant) stored,
  fully_booked_email_sent_at timestamp with time zone,
  meeting_address text,
  meeting_notes text,
  company_name text,
  contact_person text,
  budget_blocked boolean default false not null
);

create table if not exists public.participations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  study_id bigint,
  participant_id uuid,
  status text default 'joined'::text,
  paid boolean default false,
  prescreening_answers jsonb,
  match_score integer,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  paid_at timestamp with time zone,
  paypal_batch_id text,
  rejection_reason text,
  validation_deadline timestamp with time zone,
  warning_email_sent_at timestamp with time zone,
  urgent_email_sent_at timestamp with time zone,
  auto_validated boolean default false,
  reminder_week_sent_at timestamp with time zone,
  auto_validation_deadline timestamp with time zone,
  auto_validated_email_sent_at timestamp with time zone,
  researcher_autopay_email_sent_at timestamp with time zone,
  incomplete_expires_at timestamp with time zone,
  no_show_reported_by text,
  no_show_reported_at timestamp with time zone,
  no_show_email_sent_at timestamp with time zone,
  participant_phone text,
  participant_contact_email text,
  presence_confirmed_at timestamp with time zone,
  diary_confirmed_at timestamp with time zone,
  slot_datetime timestamp with time zone,
  paid_to_bank boolean default false not null,
  exclusion_reason text
);

create table if not exists public.interviews (
  id bigint generated always as identity not null,
  study_id bigint,
  participant_id uuid,
  transcript jsonb default '[]'::jsonb,
  report text,
  status text default 'in_progress'::text,
  created_at timestamp with time zone default now(),
  completed_at timestamp with time zone,
  video_urls jsonb default '[]'::jsonb,
  match_score integer,
  quality_score integer,
  quality_detail jsonb
);

create table if not exists public.slots (
  id bigint generated always as identity not null,
  study_id bigint not null,
  datetime timestamp with time zone not null,
  taken boolean default false,
  participation_id bigint,
  created_at timestamp with time zone default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  user_id uuid,
  type text,
  amount numeric,
  description text,
  participant_id uuid,
  participant_email text,
  study_id text,
  fee numeric(10,2) default 0 not null,
  total numeric(10,2),
  paypal_order_id text,
  paypal_batch_id text,
  status text default 'pending'::text not null,
  stripe_session_id text,
  stripe_payment_intent_id text,
  stripe_transfer_id text
);

create table if not exists public.invoices (
  id text not null,
  researcher_id uuid,
  date text not null,
  amount_cents integer not null,
  amount_display text not null,
  status text default 'Payée'::text not null,
  stripe_payment_intent_id text,
  researcher_name text,
  researcher_company text,
  researcher_email text,
  created_at timestamp with time zone default now()
);

create table if not exists public.messages (
  id uuid default gen_random_uuid() not null,
  study_id text,
  study_title text,
  sender_id uuid,
  receiver_id uuid,
  content text not null,
  created_at timestamp with time zone default now(),
  read boolean default false
);

create table if not exists public.video_recordings (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  study_id bigint,
  participation_id bigint,
  storage_path text not null,
  file_name text not null,
  file_size_bytes bigint,
  duration_seconds integer,
  mime_type text default 'video/webm'::text,
  status text default 'uploaded'::text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.study_drafts (
  researcher_id uuid not null,
  draft jsonb not null,
  step integer default 0 not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.wizard_events (
  id uuid default gen_random_uuid() not null,
  researcher_id uuid,
  step integer not null,
  step_label text,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.demo_events (
  id bigint generated always as identity not null,
  event_type text not null,
  created_at timestamp with time zone default now() not null,
  user_id uuid,
  session_id text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer_url text
);

create table if not exists public.page_visits (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  session_id text not null,
  path text not null,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  user_agent text,
  is_dev boolean default false not null
);

create table if not exists public.ai_bot_visits (
  id bigint generated always as identity not null,
  visited_at timestamp with time zone default now() not null,
  bot text not null,
  path text not null,
  user_agent text,
  country text
);

create table if not exists public.client_errors (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  session_id text,
  source text not null,
  message text,
  stack text,
  path text,
  user_agent text
);

create table if not exists public.account_deletions (
  id uuid default gen_random_uuid() not null,
  original_user_id uuid not null,
  email text not null,
  first_name text,
  last_name text,
  role text,
  account_created_at timestamp with time zone,
  deleted_at timestamp with time zone default now() not null
);

-- ---------------------------------------------------------------------
-- 3. Contraintes (clés primaires, uniques, checks, puis clés étrangères)
-- ---------------------------------------------------------------------
alter table public.account_deletions add constraint account_deletions_pkey PRIMARY KEY (id);
alter table public.ai_bot_visits add constraint ai_bot_visits_pkey PRIMARY KEY (id);
alter table public.client_errors add constraint client_errors_pkey PRIMARY KEY (id);
alter table public.demo_events add constraint demo_events_pkey PRIMARY KEY (id);
alter table public.interviews add constraint interviews_pkey PRIMARY KEY (id);
alter table public.interviews add constraint interviews_study_participant_unique UNIQUE (study_id, participant_id);
alter table public.invoices add constraint invoices_pkey PRIMARY KEY (id);
alter table public.messages add constraint messages_pkey PRIMARY KEY (id);
alter table public.page_visits add constraint page_visits_pkey PRIMARY KEY (id);
alter table public.participations add constraint participations_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_lang_check CHECK ((lang = ANY (ARRAY['fr'::text, 'en'::text])));
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.slots add constraint slots_pkey PRIMARY KEY (id);
alter table public.studies add constraint studies_link_is_url CHECK (((link IS NULL) OR (link ~ '^https?://'::text)));
alter table public.studies add constraint studies_pkey PRIMARY KEY (id);
alter table public.studies add constraint studies_study_type_not_empty CHECK (((study_type IS NOT NULL) AND (study_type <> ''::text)));
alter table public.study_drafts add constraint study_drafts_pkey PRIMARY KEY (researcher_id);
alter table public.transactions add constraint transactions_pkey PRIMARY KEY (id);
alter table public.video_recordings add constraint video_recordings_pkey PRIMARY KEY (id);
alter table public.video_recordings add constraint video_recordings_status_check CHECK ((status = ANY (ARRAY['uploading'::text, 'uploaded'::text, 'processing'::text, 'ready'::text, 'error'::text])));
alter table public.wizard_events add constraint wizard_events_pkey PRIMARY KEY (id);

alter table public.demo_events add constraint demo_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.interviews add constraint interviews_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.interviews add constraint interviews_study_id_fkey FOREIGN KEY (study_id) REFERENCES studies(id) ON DELETE CASCADE;
alter table public.invoices add constraint invoices_researcher_id_fkey FOREIGN KEY (researcher_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.messages add constraint messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.messages add constraint messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.participations add constraint participations_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.participations add constraint participations_study_id_fkey FOREIGN KEY (study_id) REFERENCES studies(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.slots add constraint slots_participation_id_fkey FOREIGN KEY (participation_id) REFERENCES participations(id) ON DELETE SET NULL;
alter table public.slots add constraint slots_study_id_fkey FOREIGN KEY (study_id) REFERENCES studies(id) ON DELETE CASCADE;
alter table public.study_drafts add constraint study_drafts_researcher_id_fkey FOREIGN KEY (researcher_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_recordings add constraint video_recordings_participation_id_fkey FOREIGN KEY (participation_id) REFERENCES participations(id) ON DELETE CASCADE;
alter table public.video_recordings add constraint video_recordings_study_id_fkey FOREIGN KEY (study_id) REFERENCES studies(id) ON DELETE CASCADE;
alter table public.video_recordings add constraint video_recordings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wizard_events add constraint wizard_events_researcher_id_fkey FOREIGN KEY (researcher_id) REFERENCES profiles(id) ON DELETE CASCADE;

-- ---------------------------------------------------------------------
-- 4. Index
-- ---------------------------------------------------------------------
CREATE INDEX ai_bot_visits_bot_visited_at_idx ON public.ai_bot_visits USING btree (bot, visited_at DESC);
CREATE INDEX ai_bot_visits_path_idx ON public.ai_bot_visits USING btree (path);
CREATE INDEX ai_bot_visits_visited_at_idx ON public.ai_bot_visits USING btree (visited_at DESC);
CREATE INDEX idx_interviews_participant_id ON public.interviews USING btree (participant_id);
CREATE INDEX idx_interviews_status ON public.interviews USING btree (status);
CREATE INDEX idx_invoices_researcher_id ON public.invoices USING btree (researcher_id);
CREATE INDEX idx_messages_sender_id ON public.messages USING btree (sender_id);
CREATE INDEX idx_messages_study_id ON public.messages USING btree (study_id, created_at);
CREATE INDEX idx_participations_owed ON public.participations USING btree (participant_id) WHERE ((paid = true) AND (paid_to_bank = false));
CREATE INDEX idx_participations_participant_id ON public.participations USING btree (participant_id);
CREATE INDEX idx_participations_status ON public.participations USING btree (status);
CREATE INDEX idx_participations_study_id ON public.participations USING btree (study_id);
CREATE INDEX idx_participations_study_status ON public.participations USING btree (study_id, status);
CREATE INDEX idx_profiles_payout_fingerprint ON public.profiles USING btree (payout_fingerprint) WHERE (payout_fingerprint IS NOT NULL);
CREATE INDEX idx_studies_researcher_id ON public.studies USING btree (researcher_id);
CREATE INDEX idx_studies_status ON public.studies USING btree (status);
CREATE INDEX idx_study_drafts_updated_at ON public.study_drafts USING btree (updated_at DESC);
CREATE INDEX idx_transactions_participant_id ON public.transactions USING btree (participant_id);
CREATE INDEX idx_transactions_study_id ON public.transactions USING btree (study_id);
CREATE INDEX idx_transactions_user_id ON public.transactions USING btree (user_id);
CREATE INDEX idx_video_recordings_study_id ON public.video_recordings USING btree (study_id);
CREATE INDEX idx_video_recordings_user_id ON public.video_recordings USING btree (user_id);
CREATE INDEX page_visits_created_at_idx ON public.page_visits USING btree (created_at);
CREATE INDEX page_visits_is_dev_idx ON public.page_visits USING btree (is_dev);
CREATE INDEX page_visits_session_id_idx ON public.page_visits USING btree (session_id);
CREATE INDEX slots_participation_id_idx ON public.slots USING btree (participation_id);
CREATE INDEX slots_study_id_idx ON public.slots USING btree (study_id);
CREATE INDEX wizard_events_researcher_idx ON public.wizard_events USING btree (researcher_id);
CREATE INDEX wizard_events_step_idx ON public.wizard_events USING btree (step);
CREATE UNIQUE INDEX uniq_recharge_payment_intent ON public.transactions USING btree (stripe_payment_intent_id) WHERE ((type = 'recharge'::text) AND (stripe_payment_intent_id IS NOT NULL));

-- ---------------------------------------------------------------------
-- 5. Fonctions
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.auto_confirm_email()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
begin
  update auth.users set email_confirmed_at = now() where id = new.id;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.backfill_interview_quality(p_interview_id bigint, p_score integer, p_detail jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.interviews i
     set quality_score = p_score,
         quality_detail = p_detail
   where i.id = p_interview_id
     and (
       auth.uid() = i.participant_id
       or auth.uid() in (select s.researcher_id from public.studies s where s.id = i.study_id)
     );
end;
$function$;

CREATE OR REPLACE FUNCTION public.block_study_budget(p_study_id bigint)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_study studies%rowtype;
  v_amount numeric;
  v_wallet numeric;
begin
  select * into v_study from studies
   where id = p_study_id and researcher_id = auth.uid()
   for update;
  if not found then
    raise exception 'Etude introuvable ou non autorisee';
  end if;

  if v_study.budget_blocked then
    select wallet into v_wallet from profiles where id = auth.uid();
    return v_wallet;
  end if;

  v_amount := round((coalesce(v_study.cost_per_participant,0) * coalesce(v_study.max_participants,0))::numeric, 2);

  select wallet into v_wallet from profiles where id = auth.uid() for update;
  if coalesce(v_wallet,0) < v_amount then
    raise exception 'Solde insuffisant';
  end if;

  perform set_config('app.wallet_op','1',true);
  update profiles set wallet = round((coalesce(wallet,0) - v_amount)::numeric,2)
   where id = auth.uid();
  update studies set budget_blocked = true where id = p_study_id;

  select wallet into v_wallet from profiles where id = auth.uid();
  return v_wallet;
end;
$function$;

CREATE OR REPLACE FUNCTION public.check_email_role(p_email text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select role from public.profiles where lower(email) = lower(p_email) limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.claim_fully_booked_email(p_study_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_row_count integer;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.participations
    WHERE study_id = p_study_id AND participant_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'Non autorise';
  END IF;

  UPDATE public.studies
  SET fully_booked_email_sent_at = now()
  WHERE id = p_study_id
    AND fully_booked_email_sent_at IS NULL;
  GET DIAGNOSTICS v_row_count = ROW_COUNT;
  RETURN v_row_count > 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.confirm_email_change(p_uid uuid, p_token text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_new text;
BEGIN
  SELECT pending_email INTO v_new
    FROM public.profiles
   WHERE id = p_uid
     AND verification_token IS NOT NULL
     AND verification_token = p_token
     AND pending_email IS NOT NULL;

  IF v_new IS NULL THEN
    RAISE EXCEPTION 'Lien de confirmation invalide ou expire';
  END IF;

  IF EXISTS (SELECT 1 FROM public.profiles WHERE lower(email) = v_new AND id <> p_uid)
     OR EXISTS (SELECT 1 FROM auth.users WHERE lower(email) = v_new AND id <> p_uid) THEN
    -- Quelqu'un d'autre a pris cette adresse entre-temps : on annule proprement.
    UPDATE public.profiles SET pending_email = NULL, verification_token = NULL WHERE id = p_uid;
    RAISE EXCEPTION 'Cette adresse email vient d''etre prise par un autre compte';
  END IF;

  UPDATE public.profiles
     SET email = v_new, pending_email = NULL, verification_token = NULL, email_verified = true
   WHERE id = p_uid;

  UPDATE auth.users
     SET email = v_new,
         email_confirmed_at = now(),
         email_change = '',
         email_change_token_current = '',
         email_change_token_new = '',
         updated_at = now()
   WHERE id = p_uid;

  UPDATE auth.identities
     SET identity_data = jsonb_set(jsonb_set(coalesce(identity_data,'{}'::jsonb), '{email}', to_jsonb(v_new)), '{email_verified}', 'true'::jsonb),
         updated_at = now()
   WHERE user_id = p_uid AND provider = 'email';

  RETURN v_new;
END;
$function$;

CREATE OR REPLACE FUNCTION public.email_exists(p_email text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select role from profiles where lower(email) = lower(p_email) limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.enforce_participation_quota()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_max integer;
  v_count integer;
begin
  -- Verrouille la ligne de l'étude pour sérialiser les insertions concurrentes
  select max_participants into v_max
  from public.studies
  where id = new.study_id
  for update;

  if v_max is null then
    return new; -- étude introuvable, on laisse la FK gérer l'erreur
  end if;

  select count(*) into v_count
  from public.participations
  where study_id = new.study_id
    and status in ('joined','interview','pending_validation','completed');

  if v_count >= v_max then
    raise exception 'Quota de participants atteint pour cette étude (% / %)', v_count, v_max
      using errcode = 'P0001';
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_my_studies()
 RETURNS SETOF studies
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select *
  from public.studies
  where researcher_id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.get_slot_availability(p_study_ids bigint[])
 RETURNS TABLE(study_id bigint, total integer, free integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select s.study_id, count(*)::integer as total,
         count(*) filter (where s.taken = false)::integer as free
  from public.slots s
  where s.study_id = any(p_study_ids)
  group by s.study_id;
$function$;

CREATE OR REPLACE FUNCTION public.get_study_occupancy(p_study_ids bigint[])
 RETURNS TABLE(study_id bigint, occupied integer)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select p.study_id, count(*)::integer as occupied
  from participations p
  where p.study_id = any(p_study_ids)
    and p.status in ('joined','interview','pending_validation','completed')
    and p.incomplete_expires_at is null
  group by p.study_id;
$function$;

CREATE OR REPLACE FUNCTION public.guard_interview_terminal_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if coalesce(auth.role(), '') = 'service_role' then
    return new;
  end if;

  if old.status in ('abandoned','rejected')
     and new.status is distinct from old.status then
    raise exception 'Entretien dans un etat terminal (%) : changement de statut non autorise', old.status;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.guard_participation_payment_fields()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if coalesce(auth.role(), '') = 'service_role' then
    return new;
  end if;

  if new.paid is not distinct from old.paid
     and new.paid_to_bank is not distinct from old.paid_to_bank
     and new.paid_at is not distinct from old.paid_at then
    return new;
  end if;

  if exists (
    select 1 from public.studies s
    where s.id = new.study_id and s.researcher_id = auth.uid()
  ) then
    return new;
  end if;

  raise exception 'Modification du statut de paiement non autorisee';
end;
$function$;

CREATE OR REPLACE FUNCTION public.guard_participation_terminal_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if coalesce(auth.role(), '') = 'service_role' then
    return new;
  end if;

  if old.status in ('abandoned','rejected','expired_unclaimed')
     and new.status is distinct from old.status then
    raise exception 'Participation dans un etat terminal (%) : changement de statut non autorise', old.status;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.guard_profile_wallet()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if new.wallet is not distinct from old.wallet then
    return new;
  end if;

  if coalesce(auth.role(), '') = 'service_role' then
    return new;
  end if;

  if current_setting('app.wallet_op', true) = '1' then
    return new;
  end if;

  raise exception 'Modification directe du solde non autorisee';
end;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update auth.users set email_confirmed_at = now() where id = new.id;
  insert into public.profiles (id, email, first_name, last_name, role, company, profession, profession_other, wallet, utm_source, utm_medium, utm_campaign, referrer_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'first_name', ''),
    coalesce(new.raw_user_meta_data->>'last_name', ''),
    coalesce(new.raw_user_meta_data->>'role', 'researcher'),
    new.raw_user_meta_data->>'company',
    new.raw_user_meta_data->>'profession',
    new.raw_user_meta_data->>'profession_other',
    0,
    new.raw_user_meta_data->>'utm_source',
    new.raw_user_meta_data->>'utm_medium',
    new.raw_user_meta_data->>'utm_campaign',
    new.raw_user_meta_data->>'referrer_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.has_joined_study(study_id_param bigint)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.participations pa
    WHERE pa.study_id = study_id_param AND pa.participant_id = auth.uid()
  );
$function$;

CREATE OR REPLACE FUNCTION public.increment_wallet(p_profile_id uuid, p_amount numeric)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  update public.profiles
  set wallet = wallet + p_amount
  where id = p_profile_id;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(
    (select lower(email) = 'contact@getstudyreach.com'
       from profiles where id = auth.uid()),
    false);
$function$;

CREATE OR REPLACE FUNCTION public.is_researcher()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce((select role = 'researcher' from public.profiles where id = auth.uid()), false);
$function$;

CREATE OR REPLACE FUNCTION public.is_suspended()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce((select suspended from public.profiles where id = auth.uid()), false);
$function$;

-- La clé "apikey" ci-dessous est la clé ANON (publique par conception, déjà
-- présente dans le front). Ce n'est PAS la service_role.
CREATE OR REPLACE FUNCTION public.notify_study_fully_booked()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_free  int;
  v_email text;
  v_first text;
  v_title text;
BEGIN
  IF NEW.taken = true AND (OLD.taken IS DISTINCT FROM true) THEN
    SELECT count(*) INTO v_free
    FROM public.slots
    WHERE study_id = NEW.study_id AND taken = false;

    IF v_free = 0 THEN
      SELECT p.email, p.first_name, s.title
        INTO v_email, v_first, v_title
      FROM public.studies s
      JOIN public.profiles p ON p.id = s.researcher_id
      WHERE s.id = NEW.study_id;

      IF v_email IS NOT NULL THEN
        PERFORM net.http_post(
          url     := 'https://bwaoxwfkqqpqvtpynwzh.supabase.co/functions/v1/send-email',
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YW94d2ZrcXFwcXZ0cHlud3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2OTEzMDEsImV4cCI6MjA5NjI2NzMwMX0.utS5lj2nI-Bs0efelpaj9LHT3B_MSib5Ro8ESIz1-q8'
          ),
          body := jsonb_build_object(
            'type', 'study_fully_booked',
            'data', jsonb_build_object(
              'email', v_email,
              'first_name', coalesce(v_first, ''),
              'study_title', v_title
            )
          ),
          timeout_milliseconds := 15000
        );
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refund_reject_participation(p_participation_id bigint)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_part participations%rowtype;
  v_study studies%rowtype;
  v_wallet numeric;
begin
  -- Verrou : sérialise tout appel concurrent sur CETTE participation.
  select * into v_part from participations where id = p_participation_id for update;
  if not found then
    raise exception 'Participation introuvable';
  end if;

  select * into v_study from studies
   where id = v_part.study_id and researcher_id = auth.uid();
  if not found then
    raise exception 'Non autorise';
  end if;

  if v_part.paid = true then
    raise exception 'Participation deja validee et creditee';
  end if;

  -- Une participation déjà auto-validée (J14) a une garantie de paiement à J30 :
  -- on ne doit jamais pouvoir la refuser/rembourser après coup.
  if v_part.auto_validated = true then
    raise exception 'Participation deja auto-validee : paiement garanti, refus impossible';
  end if;

  if v_part.status = 'rejected' then
    select wallet into v_wallet from profiles where id = auth.uid();
    return v_wallet;
  end if;

  update participations set status = 'rejected' where id = p_participation_id;
  update interviews set status = 'rejected'
   where study_id = v_part.study_id and participant_id = v_part.participant_id
     and status = 'pending_validation';

  perform set_config('app.wallet_op','1',true);
  update profiles set wallet = round((coalesce(wallet,0) + coalesce(v_study.cost_per_participant,0))::numeric,2)
   where id = auth.uid();

  select wallet into v_wallet from profiles where id = auth.uid();
  return v_wallet;
end;
$function$;

CREATE OR REPLACE FUNCTION public.refund_study_close(p_study_id bigint)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_study studies%rowtype;
  v_validated int;
  v_rejected int;
  v_refund_slots int;
  v_refund numeric;
  v_wallet numeric;
begin
  -- Verrou : sérialise tout appel concurrent sur CETTE étude.
  select * into v_study from studies
   where id = p_study_id and researcher_id = auth.uid() for update;
  if not found then
    raise exception 'Etude introuvable ou non autorisee';
  end if;

  if v_study.status = 'closed' then
    select wallet into v_wallet from profiles where id = auth.uid();
    return v_wallet;
  end if;

  -- "validés" = paiement déjà effectué OU déjà garanti par l'auto-validation J14.
  select count(*) into v_validated from participations
    where study_id = p_study_id and (paid = true or auto_validated = true);
  -- "rejected" = déjà remboursé au refus manuel. "abandoned" = déjà remboursé par
  -- le cron expire-participations (24h). Ne pas recompter (double remboursement).
  select count(*) into v_rejected from participations
    where study_id = p_study_id and status in ('rejected','abandoned');

  v_refund_slots := greatest(0, coalesce(v_study.max_participants,0) - v_validated - v_rejected);
  v_refund := round((v_refund_slots * coalesce(v_study.cost_per_participant,0))::numeric, 2);

  update studies set status = 'closed' where id = p_study_id;
  update participations set status = 'rejected'
   where study_id = p_study_id and status in ('pending_validation','joined','interview')
     and auto_validated is distinct from true;

  if v_refund > 0 then
    perform set_config('app.wallet_op','1',true);
    update profiles set wallet = round((coalesce(wallet,0) + v_refund)::numeric,2)
     where id = auth.uid();
  end if;

  select wallet into v_wallet from profiles where id = auth.uid();
  return v_wallet;
end;
$function$;

CREATE OR REPLACE FUNCTION public.request_email_change(p_new_email text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_new text := lower(trim(p_new_email));
  v_current text;
  v_token text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Non authentifie';
  END IF;
  IF v_new IS NULL OR v_new !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    RAISE EXCEPTION 'Adresse email invalide';
  END IF;

  SELECT lower(email) INTO v_current FROM public.profiles WHERE id = auth.uid();
  IF v_new = v_current THEN
    RAISE EXCEPTION 'C''est deja votre adresse actuelle';
  END IF;

  IF EXISTS (SELECT 1 FROM public.profiles WHERE lower(email) = v_new AND id <> auth.uid())
     OR EXISTS (SELECT 1 FROM auth.users WHERE lower(email) = v_new AND id <> auth.uid()) THEN
    RAISE EXCEPTION 'Cette adresse email est deja utilisee';
  END IF;

  v_token := replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','');

  UPDATE public.profiles
     SET pending_email = v_new, verification_token = v_token
   WHERE id = auth.uid();

  RETURN v_token;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_validation_deadline()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
  if new.status = 'pending_validation'
     and (old.status is distinct from new.status or old.status is null) then
    new.validation_deadline := now() + interval '30 days';
    new.auto_validation_deadline := now() + interval '14 days';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.study_slot_stats(p_study_id bigint)
 RETURNS TABLE(total bigint, free bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    count(*)::bigint AS total,
    count(*) FILTER (WHERE taken = false)::bigint AS free
  FROM public.slots
  WHERE study_id = p_study_id;
$function$;

CREATE OR REPLACE FUNCTION public.study_slot_stats_by_datetime(p_study_id bigint)
 RETURNS TABLE(slot_datetime timestamp with time zone, capacity bigint, free bigint, is_full boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    datetime AS slot_datetime,
    count(*)::bigint AS capacity,
    count(*) FILTER (WHERE taken = false)::bigint AS free,
    bool_and(taken) AS is_full
  FROM public.slots
  WHERE study_id = p_study_id
  GROUP BY datetime
  ORDER BY datetime;
$function$;

CREATE OR REPLACE FUNCTION public.update_video_recordings_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.verify_email(p_uid uuid, p_token text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  matched boolean;
BEGIN
  UPDATE public.profiles
     SET email_verified = true,
         verification_token = NULL
   WHERE id = p_uid
     AND verification_token IS NOT NULL
     AND verification_token = p_token
     AND email_verified = false;
  GET DIAGNOSTICS matched = ROW_COUNT;
  -- Renvoie true si on vient de valider, OU si déjà vérifié (lien cliqué 2 fois).
  RETURN matched OR EXISTS (SELECT 1 FROM public.profiles WHERE id = p_uid AND email_verified = true);
END;
$function$;

-- ---------------------------------------------------------------------
-- 6. Triggers
-- ---------------------------------------------------------------------
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
CREATE TRIGGER trg_enforce_participation_quota BEFORE INSERT ON public.participations FOR EACH ROW WHEN ((new.status = ANY (ARRAY['joined'::text, 'interview'::text]))) EXECUTE FUNCTION enforce_participation_quota();
CREATE TRIGGER trg_guard_interview_terminal_status BEFORE UPDATE ON public.interviews FOR EACH ROW EXECUTE FUNCTION guard_interview_terminal_status();
CREATE TRIGGER trg_guard_participation_payment BEFORE UPDATE ON public.participations FOR EACH ROW EXECUTE FUNCTION guard_participation_payment_fields();
CREATE TRIGGER trg_guard_participation_terminal_status BEFORE UPDATE ON public.participations FOR EACH ROW EXECUTE FUNCTION guard_participation_terminal_status();
CREATE TRIGGER trg_guard_profile_wallet BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION guard_profile_wallet();
CREATE TRIGGER trg_set_validation_deadline BEFORE INSERT OR UPDATE ON public.participations FOR EACH ROW EXECUTE FUNCTION set_validation_deadline();
CREATE TRIGGER trg_study_fully_booked AFTER UPDATE OF taken ON public.slots FOR EACH ROW EXECUTE FUNCTION notify_study_fully_booked();
CREATE TRIGGER video_recordings_updated_at BEFORE UPDATE ON public.video_recordings FOR EACH ROW EXECUTE FUNCTION update_video_recordings_updated_at();

-- ---------------------------------------------------------------------
-- 7. Vues
-- ---------------------------------------------------------------------
create or replace view public.ai_bot_visits_daily with (security_invoker = true) as
 SELECT (date_trunc('day'::text, visited_at))::date AS day,
    bot,
    count(*) AS visits,
    count(DISTINCT path) AS pages
   FROM ai_bot_visits
  GROUP BY ((date_trunc('day'::text, visited_at))::date), bot
  ORDER BY ((date_trunc('day'::text, visited_at))::date) DESC, bot;

create or replace view public.profiles_public with (security_barrier = true, security_invoker = true) as
 SELECT id, created_at, first_name, last_name, role, company, profession, age, region, themes, bio,
    birth_date, genre, city, country, nationality, status_pro, sector, education, company_size,
    seniority, devices, os, app_usage, tech_level, connection_speed, social_networks,
    has_participated, has_camera, languages, mobile, long_term, sport, diet, smoker, alcohol,
    income, online_purchase_freq, has_car, subscriptions, grocery_budget, brand_preference,
    financial_products, family_status, children_count, housing_status, housing_type, screen_time,
    media_consumption, social_frequency, creative_hobby, lang, suspended, email
   FROM profiles;

-- ---------------------------------------------------------------------
-- 8. Row Level Security + policies
-- ---------------------------------------------------------------------
alter table public.account_deletions enable row level security;
alter table public.ai_bot_visits enable row level security;
alter table public.client_errors enable row level security;
alter table public.demo_events enable row level security;
alter table public.interviews enable row level security;
alter table public.invoices enable row level security;
alter table public.messages enable row level security;
alter table public.page_visits enable row level security;
alter table public.participations enable row level security;
alter table public.profiles enable row level security;
alter table public.slots enable row level security;
alter table public.studies enable row level security;
alter table public.study_drafts enable row level security;
alter table public.transactions enable row level security;
alter table public.video_recordings enable row level security;
alter table public.wizard_events enable row level security;

create policy "Active studies are publicly viewable" on public.studies as PERMISSIVE for SELECT to anon
  using ((status = 'active'::text));
create policy "Admin can view all drafts" on public.study_drafts as PERMISSIVE for SELECT to public
  using (is_admin());
create policy "Allow anonymous insert" on public.demo_events as PERMISSIVE for INSERT to anon
  with check (true);
create policy "Participant books slot" on public.slots as PERMISSIVE for UPDATE to public
  using (((taken = false) AND (study_id IN ( SELECT participations.study_id
   FROM participations
  WHERE (participations.participant_id = auth.uid())))))
  with check (((study_id IN ( SELECT participations.study_id
   FROM participations
  WHERE (participations.participant_id = auth.uid()))) AND (participation_id IN ( SELECT participations.id
   FROM participations
  WHERE (participations.participant_id = auth.uid())))));
create policy "Participant reads available slots" on public.slots as PERMISSIVE for SELECT to public
  using (((taken = false) OR (participation_id IN ( SELECT participations.id
   FROM participations
  WHERE (participations.participant_id = auth.uid())))));
create policy "Participants and researchers can update participations" on public.participations as PERMISSIVE for UPDATE to authenticated
  using (((auth.uid() = participant_id) OR (auth.uid() IN ( SELECT studies.researcher_id
   FROM studies
  WHERE (studies.id = participations.study_id)))))
  with check (((auth.uid() = participant_id) OR (auth.uid() IN ( SELECT studies.researcher_id
   FROM studies
  WHERE (studies.id = participations.study_id)))));
create policy "Participants can insert their own interviews" on public.interviews as PERMISSIVE for INSERT to authenticated
  with check ((auth.uid() = participant_id));
create policy "Participants can insert their own participations" on public.participations as PERMISSIVE for INSERT to authenticated
  with check ((auth.uid() = participant_id));
create policy "Participants can update their own interviews" on public.interviews as PERMISSIVE for UPDATE to authenticated
  using ((auth.uid() = participant_id))
  with check ((auth.uid() = participant_id));
create policy "Participants can view their own interviews" on public.interviews as PERMISSIVE for SELECT to authenticated
  using (((auth.uid() = participant_id) OR (auth.uid() IN ( SELECT studies.researcher_id
   FROM studies
  WHERE (studies.id = interviews.study_id)))));
create policy "Participants can view their own participations" on public.participations as PERMISSIVE for SELECT to authenticated
  using (((auth.uid() = participant_id) OR (auth.uid() IN ( SELECT studies.researcher_id
   FROM studies
  WHERE (studies.id = participations.study_id)))));
create policy "Researcher manages own draft" on public.study_drafts as PERMISSIVE for ALL to public
  using ((( SELECT auth.uid() AS uid) = researcher_id))
  with check ((( SELECT auth.uid() AS uid) = researcher_id));
create policy "Researcher manages own slots" on public.slots as PERMISSIVE for ALL to public
  using ((study_id IN ( SELECT studies.id
   FROM studies
  WHERE (studies.researcher_id = auth.uid()))));
create policy "Researchers can delete their own studies" on public.studies as PERMISSIVE for DELETE to authenticated
  using ((auth.uid() = researcher_id));
create policy "Researchers can insert their own studies" on public.studies as PERMISSIVE for INSERT to authenticated
  with check ((auth.uid() = researcher_id));
create policy "Researchers can insert their own wizard events" on public.wizard_events as PERMISSIVE for INSERT to authenticated
  with check ((researcher_id = auth.uid()));
create policy "Researchers can update their own studies" on public.studies as PERMISSIVE for UPDATE to authenticated
  using ((auth.uid() = researcher_id))
  with check ((auth.uid() = researcher_id));
create policy "Researchers can view recordings for their studies" on public.video_recordings as PERMISSIVE for SELECT to public
  using ((study_id IN ( SELECT studies.id
   FROM studies
  WHERE (studies.researcher_id = auth.uid()))));
create policy "Researchers can view their own wizard events" on public.wizard_events as PERMISSIVE for SELECT to authenticated
  using ((researcher_id = auth.uid()));
create policy "Researchers see own invoices" on public.invoices as PERMISSIVE for SELECT to public
  using ((researcher_id = auth.uid()));
create policy "Studies are viewable by authenticated users" on public.studies as PERMISSIVE for SELECT to authenticated
  using ((((status = 'active'::text) AND (NOT is_researcher())) OR (auth.uid() = researcher_id) OR is_admin() OR has_joined_study(id)));
create policy "Users can insert their own profile" on public.profiles as PERMISSIVE for INSERT to authenticated
  with check ((auth.uid() = id));
create policy "Users can manage their own video recordings" on public.video_recordings as PERMISSIVE for ALL to public
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));
create policy "Users can mark messages as read" on public.messages as PERMISSIVE for UPDATE to public
  using ((auth.uid() = receiver_id));
create policy "Users can read their messages" on public.messages as PERMISSIVE for SELECT to public
  using (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));
create policy "Users can send messages" on public.messages as PERMISSIVE for INSERT to public
  with check ((auth.uid() = sender_id));
create policy "Users can update their own profile" on public.profiles as PERMISSIVE for UPDATE to authenticated
  using ((auth.uid() = id))
  with check ((auth.uid() = id));
create policy "Users can view their own transactions" on public.transactions as PERMISSIVE for SELECT to authenticated
  using (((auth.uid() = user_id) OR (auth.uid() = participant_id)));
create policy "anon can insert client errors" on public.client_errors as PERMISSIVE for INSERT to anon
  with check (true);
create policy "anon can insert page visits" on public.page_visits as PERMISSIVE for INSERT to anon
  with check (true);
create policy block_suspended on public.interviews as RESTRICTIVE for ALL to authenticated
  using ((NOT is_suspended()))
  with check ((NOT is_suspended()));
create policy block_suspended on public.messages as RESTRICTIVE for ALL to authenticated
  using ((NOT is_suspended()))
  with check ((NOT is_suspended()));
create policy block_suspended on public.participations as RESTRICTIVE for ALL to authenticated
  using ((NOT is_suspended()))
  with check ((NOT is_suspended()));
create policy block_suspended on public.video_recordings as RESTRICTIVE for ALL to authenticated
  using ((NOT is_suspended()))
  with check ((NOT is_suspended()));
create policy deny_client_access on public.ai_bot_visits as PERMISSIVE for ALL to anon, authenticated
  using (false)
  with check (false);
create policy profiles_select_scoped on public.profiles as PERMISSIVE for SELECT to public
  using (((auth.uid() = id) OR is_admin() OR (EXISTS ( SELECT 1
   FROM (participations pa
     JOIN studies s ON ((s.id = pa.study_id)))
  WHERE ((s.researcher_id = auth.uid()) AND (pa.participant_id = profiles.id)))) OR (EXISTS ( SELECT 1
   FROM (participations pa
     JOIN studies s ON ((s.id = pa.study_id)))
  WHERE ((pa.participant_id = auth.uid()) AND (s.researcher_id = profiles.id)))) OR (is_researcher() AND (role = 'participant'::text))));
create policy researcher_update_interviews on public.interviews as PERMISSIVE for UPDATE to public
  using ((auth.uid() IN ( SELECT s.researcher_id
   FROM studies s
  WHERE (s.id = interviews.study_id))))
  with check ((auth.uid() IN ( SELECT s.researcher_id
   FROM studies s
  WHERE (s.id = interviews.study_id))));
create policy service_role_full_access_account_deletions on public.account_deletions as PERMISSIVE for ALL to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------
-- 9. Droits d'exécution des fonctions (qui peut appeler quoi via l'API)
-- ---------------------------------------------------------------------
revoke execute on all functions in schema public from public, anon, authenticated;

-- service_role uniquement (fonctions internes, appelées par le backend / triggers)
grant execute on function public.auto_confirm_email() to service_role;
grant execute on function public.email_exists(text) to service_role;
grant execute on function public.enforce_participation_quota() to service_role;
grant execute on function public.handle_new_user() to service_role;
grant execute on function public.increment_wallet(uuid, numeric) to service_role;
grant execute on function public.notify_study_fully_booked() to service_role;

-- utilisateurs connectés + service_role
grant execute on function public.backfill_interview_quality(bigint, integer, jsonb) to authenticated, service_role;
grant execute on function public.block_study_budget(bigint) to authenticated, service_role;
grant execute on function public.claim_fully_booked_email(bigint) to authenticated, service_role;
grant execute on function public.get_my_studies() to authenticated, service_role;
grant execute on function public.has_joined_study(bigint) to authenticated, service_role;
grant execute on function public.is_suspended() to authenticated, service_role;
grant execute on function public.refund_reject_participation(bigint) to authenticated, service_role;
grant execute on function public.refund_study_close(bigint) to authenticated, service_role;
grant execute on function public.request_email_change(text) to authenticated, service_role;

-- visiteurs (anon) + connectés + service_role
grant execute on function public.check_email_role(text) to anon, authenticated, service_role;
grant execute on function public.confirm_email_change(uuid, text) to anon, authenticated, service_role;
grant execute on function public.get_slot_availability(bigint[]) to anon, authenticated, service_role;
grant execute on function public.get_study_occupancy(bigint[]) to anon, authenticated, service_role;
grant execute on function public.guard_interview_terminal_status() to anon, authenticated, service_role;
grant execute on function public.guard_participation_payment_fields() to anon, authenticated, service_role;
grant execute on function public.guard_participation_terminal_status() to anon, authenticated, service_role;
grant execute on function public.guard_profile_wallet() to anon, authenticated, service_role;
grant execute on function public.is_admin() to anon, authenticated, service_role;
grant execute on function public.is_researcher() to anon, authenticated, service_role;
grant execute on function public.set_validation_deadline() to anon, authenticated, service_role;
grant execute on function public.study_slot_stats(bigint) to anon, authenticated, service_role;
grant execute on function public.study_slot_stats_by_datetime(bigint) to anon, authenticated, service_role;
grant execute on function public.update_video_recordings_updated_at() to anon, authenticated, service_role;
grant execute on function public.verify_email(uuid, text) to anon, authenticated, service_role;

-- Droits par colonne sur "studies" : les colonnes internes (budget, budget_blocked,
-- fully_booked_email_sent_at, global_synthesis) ne sont PAS lisibles directement
-- par anon/authenticated (le chercheur lit tout via la fonction get_my_studies()).
revoke select on public.studies from anon, authenticated;
grant select (id, created_at, title, theme, duration, mode, link, cost_per_participant, researcher_id,
  status, study_type, link_ai, target_criteria, max_participants, prescreening, ai, description,
  ai_focus, ai_response_format, meeting_address, meeting_notes, company_name, contact_person)
  on public.studies to anon, authenticated;

-- ---------------------------------------------------------------------
-- 10. Storage : bucket privé des vidéos d'entretien + policies
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public) values ('interview-videos', 'interview-videos', false)
on conflict (id) do nothing;

create policy "Authenticated users can upload videos" on storage.objects as PERMISSIVE for INSERT to authenticated
  with check ((bucket_id = 'interview-videos'::text));
create policy "Participants can upload their own interview videos" on storage.objects as PERMISSIVE for INSERT to authenticated
  with check (((bucket_id = 'interview-videos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "Participants can view their own interview videos" on storage.objects as PERMISSIVE for SELECT to authenticated
  using (((bucket_id = 'interview-videos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "Researchers can view participant interview videos" on storage.objects as PERMISSIVE for SELECT to authenticated
  using (((bucket_id = 'interview-videos'::text) AND (EXISTS ( SELECT 1
   FROM (interviews iv
     JOIN studies s ON ((s.id = iv.study_id)))
  WHERE ((s.researcher_id = auth.uid()) AND ((storage.foldername(objects.name))[1] = (iv.participant_id)::text))))));
create policy "Users can delete their own videos" on storage.objects as PERMISSIVE for DELETE to authenticated
  using (((bucket_id = 'interview-videos'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));
create policy "Users can view their own videos" on storage.objects as PERMISSIVE for SELECT to authenticated
  using (((bucket_id = 'interview-videos'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

-- ---------------------------------------------------------------------
-- 11. Tâches planifiées (pg_cron) qui appellent les Edge Functions
-- (clé "apikey" = clé ANON publique)
-- ---------------------------------------------------------------------
select cron.schedule('check-noshow-slots-every-10min', '2-59/10 * * * *', $cron$
  select net.http_post(
    url := 'https://bwaoxwfkqqpqvtpynwzh.supabase.co/functions/v1/check-noshow-slots',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YW94d2ZrcXFwcXZ0cHlud3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2OTEzMDEsImV4cCI6MjA5NjI2NzMwMX0.utS5lj2nI-Bs0efelpaj9LHT3B_MSib5Ro8ESIz1-q8'
    ),
    body := '{}'::jsonb
  );
$cron$);

select cron.schedule('check-validation-deadlines-hourly', '5 * * * *', $cron$
  select net.http_post(
    url := 'https://bwaoxwfkqqpqvtpynwzh.supabase.co/functions/v1/check-validation-deadlines',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YW94d2ZrcXFwcXZ0cHlud3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2OTEzMDEsImV4cCI6MjA5NjI2NzMwMX0.utS5lj2nI-Bs0efelpaj9LHT3B_MSib5Ro8ESIz1-q8'
    ),
    body := '{}'::jsonb
  );
$cron$);

select cron.schedule('daily-signup-digest', '8 7 * * *', $cron$
  select net.http_post(
    url := 'https://bwaoxwfkqqpqvtpynwzh.supabase.co/functions/v1/daily-signup-digest',
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
$cron$);

select cron.schedule('expire-stale-participations', '0 * * * *', $cron$
  SELECT net.http_post(
    url := 'https://bwaoxwfkqqpqvtpynwzh.supabase.co/functions/v1/expire-participations',
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
$cron$);
